import cv2
o = cv2.imread("D:/photo/cat2.webp")
Sobelx = cv2.Sobel(o,cv2.CV_64F,1,0)
Sobely = cv2.Sobel(o,cv2.CV_64F,0,1)
Sobelx = cv2.convertScaleAbs(Sobelx)
Sobely = cv2.convertScaleAbs(Sobely)
Sobelxy1 = cv2.addWeighted(Sobelx,0.5,Sobely,0.5,0)
Sobelxy2 = cv2.Sobel(o,cv2.CV_64F,1,1)
Sobelxy2 = cv2.convertScaleAbs(Sobelxy2)
cv2.imshow("original",o)
cv2.imshow("xy1",Sobelxy1)
cv2.imshow("xy2",Sobelxy2)
cv2.waitKey()
cv2.destroyAllWindows()