import cv2
import numpy as np
o = cv2.imread("D:/photo/wen.webp")
cv2.imshow("original",o)
gray = cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
ret,binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
contours,hierarchy = cv2.findContours(binary,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
mask1 = np.zeros(gray.shape,np.uint8)
cv2.drawContours(mask1,[cnt],0,255,2)
points1 = cv2.findNonZero(mask1)
print("points1_shape",points1.shape)
print("point1",points1)
cv2.imshow("mask1",mask1)
mask2 = np.zeros(gray.shape,np.uint8)
cv2.drawContours(mask2,[cnt],-1,(255,255,0),-1)
points2 = cv2.findNonZero(mask2)
print("points2",points2)
cv2.imshow("mask2",mask2)
cv2.waitKey()
cv2.destroyAllWindows()