import cv2
o1 = cv2.imread("D:/photo/wen.webp",0)
o2 = cv2.imread("D:/photo/cat.webp",0)
o3 = cv2.imread("D:/photo/cat2.webp",0)
HUM1 = cv2.HuMoments(cv2.moments(o1)).flatten()
HUM2 = cv2.HuMoments(cv2.moments(o2)).flatten()
HUM3 = cv2.HuMoments(cv2.moments(o3)).flatten()
print("o1.shape=",o1.shape)
print("o2.shape=",o2.shape)
print("o3.shape=",o3.shape)
print("cv2.moments(o1)=",cv2.moments(o1))
print("cv2.moments(o2)=",cv2.moments(o2))
print("cv2.moments(o3)=",cv2.moments(o3))
print("\nHuM1=\n",HUM1)
print("\nHuM2=\n",HUM2)
print("\nHuM3=\n",HUM3)
print("\nHuM1-HuM2\n",HUM1-HUM2)
print("\nHuM1-HuM3\n",HUM1-HUM3)
cv2.imshow("o1",o1)
cv2.imshow("o2",o2)
cv2.imshow("o3",o3)
cv2.waitKey()
cv2.destroyAllWindows()